### ISSUE TITLE
Checklist for May 2022 data rollout

### ISSUE THREAD

**Issue by kaizadp** [COMPASS-DOE/EXCHANGE#14]
- [x] Do any last minute data cleaning...

- [x] Make sure data file names follow THIS structure: CAMPAIGN_TYPE OF SAMPLE_ANALYSIS TYPE_LEVEL OF QC_DATE

- [x] Merge all GitHub Branches

- [x] Spot Check Datasets for missing data

- [x] Create a list of what analyses are done on what kits. @kaizadp 

- [x] Clone the GitHub data to GDrive. Set folders.

- [x] Double check everything

- [x] MOVE to the EXTERNAL data folder

@stephpenn1 @kaizadp
